// One-time (re-runnable) font vendoring script.
//
// Downloads the woff2 files for the three site typefaces and writes
// src/styles/fonts.css with local @font-face declarations, so the site no
// longer depends on Google Fonts / Fontshare at runtime. Re-run with
// `node scripts/fetch-fonts.mjs` to refresh (e.g. new weights).
//
// Google faces are subsetted (we keep latin + latin-ext; unicode-range gates
// the rest away). Fontshare serves the full face per weight.

import { writeFileSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, '..')
const FONT_DIR = resolve(root, 'public/fonts')
mkdirSync(FONT_DIR, { recursive: true })

const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'

const KEEP_SUBSETS = new Set(['latin', 'latin-ext'])
const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')
const subsetTag = (s) => s.replace('-ext', 'ext')

async function getText(url) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } })
  if (!res.ok) throw new Error(`Fetch failed ${res.status}: ${url}`)
  return res.text()
}

async function download(url, filePath) {
  const abs = url.startsWith('//') ? `https:${url}` : url
  const res = await fetch(abs, { headers: { 'User-Agent': UA } })
  if (!res.ok) throw new Error(`Download failed ${res.status}: ${abs}`)
  const buf = Buffer.from(await res.arrayBuffer())
  writeFileSync(filePath, buf)
  return buf.length
}

const faces = [] // { family, weight, file, unicodeRange }

// --- Google (Inter + JetBrains Mono): subsetted, carries unicode-range -------
async function vendorGoogle() {
  const css = await getText(
    'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap',
  )
  // Each block is preceded by a `/* subset */` comment.
  const re = /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*{([^}]*)}/g
  let m
  while ((m = re.exec(css))) {
    const subset = m[1]
    if (!KEEP_SUBSETS.has(subset)) continue
    const body = m[2]
    const family = body.match(/font-family:\s*'([^']+)'/)?.[1]
    const weight = body.match(/font-weight:\s*(\d+)/)?.[1]
    const url = body.match(/url\((https:[^)]+\.woff2)\)/)?.[1]
    const unicodeRange = body.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim()
    if (!family || !weight || !url) continue
    const file = `${slug(family)}-${weight}-${subsetTag(subset)}.woff2`
    const bytes = await download(url, resolve(FONT_DIR, file))
    faces.push({ family, weight, file, unicodeRange })
    console.log(`  ${file}  (${(bytes / 1024).toFixed(1)} kB)`)
  }
}

// --- Fontshare (Clash Display): full face per weight, no unicode-range -------
async function vendorFontshare() {
  const css = await getText(
    'https://api.fontshare.com/v2/css?f[]=clash-display@500,600,700&display=swap',
  )
  const re = /@font-face\s*{([^}]*)}/g
  let m
  while ((m = re.exec(css))) {
    const body = m[1]
    const family = body.match(/font-family:\s*'([^']+)'/)?.[1]
    const weight = body.match(/font-weight:\s*(\d+)/)?.[1]
    const url = body.match(/url\(['"]?(\/\/[^)'"]+\.woff2)['"]?\)/)?.[1]
    if (!family || !weight || !url) continue
    const file = `${slug(family)}-${weight}.woff2`
    const bytes = await download(url, resolve(FONT_DIR, file))
    faces.push({ family, weight, file })
    console.log(`  ${file}  (${(bytes / 1024).toFixed(1)} kB)`)
  }
}

console.log('Vendoring Google faces (Inter, JetBrains Mono)…')
await vendorGoogle()
console.log('Vendoring Fontshare face (Clash Display)…')
await vendorFontshare()

// --- Emit fonts.css ----------------------------------------------------------
const cssOut =
  `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n\n` +
  faces
    .map(
      (f) =>
        `@font-face {\n` +
        `  font-family: '${f.family}';\n` +
        `  font-style: normal;\n` +
        `  font-weight: ${f.weight};\n` +
        `  font-display: swap;\n` +
        `  src: url('/fonts/${f.file}') format('woff2');\n` +
        (f.unicodeRange ? `  unicode-range: ${f.unicodeRange};\n` : '') +
        `}`,
    )
    .join('\n\n') +
  '\n'

const OUT = resolve(root, 'src/styles/fonts.css')
writeFileSync(OUT, cssOut)
console.log(`\nWrote ${faces.length} @font-face rules → src/styles/fonts.css`)
